spring:
  application:
    name: siniestros
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    continue-on-error: true
    hikari:
      jdbc-url: jdbc:oracle:thin:@localhost:49161:xe
      username: siniestros
      password: ENC(+vv8G0fWFr/pfFLAcayUyk+PTu66xcEN)
      maximum-pool-size: 20
      minimum-idle: 10
      driver-class-name: oracle.jdbc.driver.OracleDriver
  cache:
    jcache:
      config: classpath:ehcache.xml
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
server:
    port: 8080
    undertow:
      accesslog:
        enabled: true
        pattern: common
        dir: logs/
logging:
  level:
    ROOT: ERROR
    org.springframework: INFO
    com.afirmeseguros: DEBUG
  pattern:
    console: '%cyan(%d{yyyy-MM-dd HH:mm:ss}) %magenta([%thread]) %highlight(%-5level) %boldWhite(%logger{0}) %green([%mdc]) --- %msg%n'
    file: '%cyan(%d{yyyy-MM-dd HH:mm:ss}) %magenta([%thread]) %highlight(%-5level) %boldWhite(%logger{0}) %green([%mdc]) --- %msg%n'
  file: logs/application.log
jasypt:
  encryptor:
    password: afirmeseguros
---
 
 spring:
   profiles: integration
---
 
 spring:
   profiles: production
---